### ISSUE TITLE
ThreadSanitizer reports in host_resolver

### ISSUE THREAD

**Issue by nchong-at-aws** [awslabs/aws-c-io#228]
1. In `source/host_resolver.c` the `last_use` variable is shared between threads so should be atomic to be data-race free. The variable is 64-bit so cannot be trivially turned into a `aws_atomic_var`, which is 32-bits on 32-bit platforms. Currently, we exclude resolver tests when running Thread Sanitizer regressions.

Failing tests when instrumented: `test_resolver_ttls`, `test_resolver_connect_failure_recording`, `test_resolver_ttl_refreshes_on_resolve`

**Comment by bretambrose** [comment]
This has been addressed by https://github.com/awslabs/aws-c-io/pull/308

Note that there is still no join on host resolver threads (it's not clear that we can retain the desired, ephemeral resolution behavior) but there are now clear invariants/signals around complete shutdown/cleanup for the resolver and its worker threads.  At this point, thread join warnings on the host resolver are now false positives (hence the suppression file).
