### ISSUE TITLE
ECC Support

### ISSUE THREAD

**Issue by anands-gr** [awslabs/aws-c-io#239]
When attempting to connect to a HTTPS website using ECC certificates I get the following error (e.g. using [elasticurl](https://github.com/awslabs/aws-c-http/blob/master/bin/elasticurl/main.c)):

```
./elasticurl https://ecc256.badssl.com
Connection failed with error aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed
```

Does the `aws_tls_ctx_options` parameter expose support for ECC keys? Alternatively is it possible to add a test case for ECC support, similar to the other [baddssl.com tests](https://github.com/awslabs/aws-c-io/blob/master/tests/tls_handler_test.c#L617)?

Thanks

**Comment by rccarper** [comment]
We're looking at a fix on our side, as well as adding the unit tests that you have suggested.  The fix shouldn't require you to make additional parameters changes in the aws_tls_ctx_options.  I should hopefully have another update for you within the next few days.

**Comment by rccarper** [comment]
We have merged a fix into master, and will be cutting a new release shortly!

**Comment by rccarper** [comment]
Release v0.4.30 of aws-c-io has the fix.  Is your project using aws-c-io through any of the CRT's?  (If so, I can cut a new release of that CRT which points at the latest version of aws-c-io.)

**Comment by anands-gr** [comment]
No, just the aws-c-http library.

**Comment by rccarper** [comment]
Okay, I'll close this issue then.  Please feel free to re-open it if you're still seeing the problem even with the fix.
