### ISSUE TITLE
Overriding the CA on Mac results in server certs to be always valid

### ISSUE THREAD

**Issue by massi-ang** [awslabs/aws-c-io#254]
I am using the [basic_pub_sub example](https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/master/samples/mqtt/basic_pub_sub/main.cpp) and passing a custom CA file results in the server certificate to be always valid.

Example:
```
./basic-pub-sub --endpoint "xxxxx-ats.iot.us-east-1.amazonaws.com" --cert device1004.pem --key privkey.pem --topic testTopic --ca_file self_signed_ca.pem
```

should fail, but works.

**Comment by justinboswell** [comment]
Merged fix. Thanks for the PR!
