### ISSUE TITLE
Windows version does provide a clear error message when trying to  import PKCS#8 encoded private keys

### ISSUE THREAD

**Issue by massi-ang** [awslabs/aws-c-io#258]
Code crashes when importing PKCS#8 encoded private keys.
See [this](https://tls.mbed.org/kb/cryptography/asn1-key-structures-in-der-and-pem) for reference of the various formats.

**Comment by jmklix** [comment]
Was this fixed with this [PR](https://github.com/awslabs/aws-c-io/pull/371)?
