### ISSUE TITLE
Support for ECC keys in Windows port

### ISSUE THREAD

**Issue by massi-ang** [awslabs/aws-c-io#261]
Looking at the code at:
https://github.com/awslabs/aws-c-io/blob/60a451a6a7269f1f99718950cd34befcf7e8a096/source/windows/windows_pki_utils.c#L333

it seems that Windows port only support RSA private keys in PKCS#1 format.

Add support for ECC keys in SEC 1 encoded format and possibly wrapped in PKCS#8.

**Comment by JonathanHenson** [comment]
We should be doing something like this here.

https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/x509_schannel.c#L97

**Comment by massi-ang** [comment]
Maybe we could also check the first line of the PEM file, as that will tell you the type of key and encoding used.

**Comment by bretambrose** [comment]
Ecc-based cert/key import on Windows should now be working correctly, per https://github.com/awslabs/aws-c-io/pull/371
