### ISSUE TITLE
Unable to import certificate PEMs encoded in UTF16

### ISSUE THREAD

**Issue by massi-ang** [awslabs/aws-c-io#280]
Saving a PEM file from the AWS Powershell tools encodes the data in UTF16.
The library is not able to correctly handle this format and fails, as it uses fread() which only works at the byte level.

**Comment by justinboswell** [comment]
That is by design. We only accept UTF-8 input for the entire API and I/O.

**Comment by justinboswell** [comment]
I am adding a BOM/encoding detection routine to our libraries, and I will add it as a lint check before we import PEMs, so you'll at least get a good error message.
