### ISSUE TITLE
Warning messages if endpoint url is invalid

### ISSUE THREAD

**Issue by TobiasJacob** [awslabs/aws-c-io#305]
Hello,

I am working under Mac OS X and with python 3.7.1 in a conda environment. Using invalid endpoint argument (iot.us-east-1.amazonaws.com) results in strange error messages. 
- First case: I suggest checking the endpoint argument for the correct format first (abcd123456wxyz-ats.iot.us-east-1.amazonaws.com).
- Second case: Also, I suggest throwing a warning if people do not use the ats endpoint (abcd123456wxyz.iot.eu-central-1.amazonaws.com). 

The first case produces the following output currently. It seems like message->allocator is not set:

''' Connecting to iot.eu-central-1.amazonaws.com with client ID 'DemoDevice'...
Fatal error condition occurred in /Users/Shared/Jenkins/Home/workspace/aws-crt-python-build-wheels-osx/aws-crt-python/aws-common-runtime/aws-c-common/source/allocator.c:176: allocator != ((void*)0)
Exiting Application
'''
...
'''
################################################################################
Raw stacktrace:
################################################################################
1   _awscrt.cpython-37m-darwin.so       0x000000010281e5e3 s_print_stack_trace + 19
2   libsystem_platform.dylib            0x00007fff685ca5fd _sigtramp + 29
3   ???                                 0x0000000000000000 0x0 + 0
4   libsystem_c.dylib                   0x00007fff684a0808 abort + 120
5   _awscrt.cpython-37m-darwin.so       0x00000001028221db aws_fatal_assert + 75
6   _awscrt.cpython-37m-darwin.so       0x0000000102821074 aws_mem_release + 52
7   _awscrt.cpython-37m-darwin.so       0x0000000102840910 s_do_read + 336
8   _awscrt.cpython-37m-darwin.so       0x00000001028402dc s_on_readable_notification + 92
9   _awscrt.cpython-37m-darwin.so       0x000000010283edde s_on_socket_io_event + 350
10  _awscrt.cpython-37m-darwin.so       0x000000010282eecc s_event_thread_main + 956
11  _awscrt.cpython-37m-darwin.so       0x000000010282bf28 thread_fn + 88
12  libsystem_pthread.dylib             0x00007fff685d6109 _pthread_start + 148
13  libsystem_pthread.dylib             0x00007fff685d1b8b thread_start + 15
'''

The second case produces:

'''
Connecting to akkh9376u0e33.iot.eu-central-1.amazonaws.com with client ID 'DemoDevice'...
Traceback (most recent call last):
  File "src/backgroundworker/sample.py", line 132, in <module>
    connect_future.result()
  File "/Users/tobiasjacob/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/tobiasjacob/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
awscrt.exceptions.AwsCrtError: AwsCrtError(name='AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE', message='TLS (SSL) negotiation failed', code=1029)
'''

**Comment by bretambrose** [comment]
Aws-c-io is intended as a general async networking framework, so validating endpoint names against a narrow pattern isn't something that would really fit here.  Even at the iot SDK level its still a bit suspect since it would lead to backwards compatibility issues should the endpoint pattern change in the future.
