### ISSUE TITLE
CPU pinning in event_loop.c

### ISSUE THREAD

**Issue by sadsiddi491** [awslabs/aws-c-io#392]
Hi,
In the follwoing code in event_loop.c, by doing AWS_ZERO_STRUCT on thread_options, thh core_id is set to 0. The aws_thread_launch then tries to pin the thread to core 0. Is this by design?. Should the default core_id be set to -1, as in default thread_options?

```
struct aws_thread_options thread_options;    
AWS_ZERO_STRUCT(thread_options);    
thread_options.join_strategy = AWS_TJS_MANAGED;
AWS_FATAL_ASSERT( aws_thread_launch(&amp;cleanup_thread, s_event_loop_destroy_async_thread_fn, el_group, &amp;thread_options) ==        AWS_OP_SUCCESS);
```

**Comment by bretambrose** [comment]
That sounds correct.  Can you make a PR with the changes?
