### ISSUE TITLE
aws-c-io includes Windows.h in public headers

### ISSUE THREAD

**Issue by pitrou** [awslabs/aws-c-io#401]
The `Windows.h` header has started being included in aws-c-io public headers, notably `aws/io/event_loop.h`. This in turns gets exposed into aws-sdk-cpp public headers, and can have repercussions on downstream users (especially due to Windows' habit of defining many macros with common names).

**Comment by bretambrose** [comment]
Fixed in https://github.com/awslabs/aws-c-io/pull/454

**Comment by pitrou** [comment]
Thank you!
