### ISSUE TITLE
Questions about "Release" and "Pre-release" tags

### ISSUE THREAD

**Issue by seemantk** [awslabs/aws-c-io#474]
hello,

I'm looking to package awscliv2 source build for Funtoo Linux, and this is in the dependency chain for that.
Funtoo has a system that can automatically bump package versions in sync with upstream.  The only thing is this package (aws-c-io) has all the tarballs tagged as prerelease.

So I guess the question is: what are the criteria before y'all tag a tarball as "Release" ?

Thank you,
seemant

**Comment by jmklix** [comment]
Latest release and future releases should no longer have the `pre-release` tag
https://github.com/awslabs/aws-c-io/releases/tag/v0.14.9
