### ISSUE TITLE
Incorrect format string in default_resolve_host

### ISSUE THREAD

**Issue by fakkeroni** [awslabs/aws-c-io#496]
aws trying to log 
`host_name->bytes`
in
`AWS_LOGF_DEBUG(AWS_LS_IO_DNS, "id=%p: Host resolution requested for %s", (void *)resolver, host_name->bytes);`
the matching format string parameter is "%s", however `host_name->bytes` is of type: 
`const uint8_t bytes[1];`
which is generally not null terminated.

**Comment by bretambrose** [comment]
A byte array in general, sure, but the bytes off the end of aws_string are always null terminated.
