### ISSUE TITLE
VSOCK socket client would almost always fail

### ISSUE THREAD

**Issue by solokacher** [awslabs/aws-c-io#576]
### Describe the bug

Function `s_update_local_endpoint(struct aws_socket *socket)` defined at
source/posix/socket.c#L273 has the following logic:
```
        /* VSOCK port is 32bit, but aws_socket_endpoint.port is only 16bit.
         * Hopefully this isn't an issue, since users can only pass in 16bit values.
         * But if it becomes an issue, we'll need to make aws_socket_endpoint more flexible */
        if (s->svm_port > UINT16_MAX) {
            AWS_LOGF_ERROR(
                AWS_LS_IO_SOCKET,
                "id=%p fd=%d: aws_socket_endpoint can't deal with VSOCK port > UINT16_MAX",
                (void *)socket,
                socket->io_handle.data.fd);
            return aws_raise_error(AWS_IO_SOCKET_INVALID_ADDRESS);
        }
        tmp_endpoint.port = (uint16_t)s->svm_port;
```

When it is used as a client, it would almost always fail, as the ephemeral port grabbed from the system is likely be large number. How did we test this code?

### Expected Behavior

aws_socket_connect() should succeed

### Current Behavior

Failure with `aws_socket_endpoint can't deal with VSOCK port > UINT16_MAX`

### Reproduction Steps

Create a client and connect to any VSOCK address

### Possible Solution

use 32 bit port number

### aws-c-io version used

version containing https://github.com/awslabs/aws-c-io/commit/df07e42286aa67d15ebe86d1de2d68c22e6eadb2

### Compiler and version used

clang14

### Operating System and version

Linux

**Comment by graebm** [comment]
VSOCK support isn't 100% complete, as you've discovered. Someone submitted this [partial support](https://github.com/awslabs/aws-c-io/pull/295), and we integrated it to unblock them, but never bound it out to [any](https://github.com/awslabs/aws-crt-python/blob/ce221859f37325d362c587ce2ef22b5ced3a4502/awscrt/io.py#L191) [other](https://github.com/awslabs/aws-crt-java/blob/89079c89ebfb9272d801fe620818f2bc9e5900ed/src/main/java/software/amazon/awssdk/crt/io/SocketOptions.java#L19) [languages](https://github.com/awslabs/aws-crt-cpp/blob/fdc9f7181c673d18fbdaa1f936ad4bf732451ac3/include/aws/crt/io/SocketOptions.h#L34).

Finishing support would mean widening `aws_socket_endpoint.port`, add error-checking anywhere we cast it gets narrowed to 16bits, widen the value in our other language bindings, etc, etc, etc. It's not on our current roadmap.

I assume you're trying to use this directly from C? What's your use case?

**Comment by graebm** [comment]
I'm working on a fix...

**Comment by graebm** [comment]
It is done
port is 32bits now everywhere
