### ISSUE TITLE
Support for truncated (as opposed to unbounded) exponential backoff

### ISSUE THREAD

**Issue by grrtrr** [awslabs/aws-c-io#583]
### Describe the feature

The original AWS post that introduced exponential backoff for request retries [used truncated exponential back-off](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/).

The `aws-c-io` supports variations of jitter:
```c
static compute_backoff_fn *s_backoff_compute_table[] = {
    [AWS_EXPONENTIAL_BACKOFF_JITTER_DEFAULT] = s_compute_full_jitter,
    [AWS_EXPONENTIAL_BACKOFF_JITTER_NONE] = s_compute_no_jitter,
    [AWS_EXPONENTIAL_BACKOFF_JITTER_FULL] = s_compute_full_jitter,
    [AWS_EXPONENTIAL_BACKOFF_JITTER_DECORRELATED] = s_compute_deccorelated_jitter,
};
```
However, none of the variants support truncated exponential back-off.

### Use Case

Truncated back-off allows the user to set a cap/maximum value of the retry interval, to suit network/load conditions, or to configure for a maximum total retry time.

This is especially important when costs are proportional to application runtime, such as services running on a kubernetes pod.

For this reason, we have had the requirement to use truncated back-off.

### Proposed Solution

Update `AWS_EXPONENTIAL_BACKOFF_JITTER_FULL` (the default) to support truncated backoff via configuration.

A maximum upper bound of `0` can disable the feature and be set as default value, to retain backward compatibility.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by waahm7** [comment]
Hi @grrtrr,

Thank you for creating the issue and PR. We have addressed this problem a bit differently in #587. Please take a look and let me know if there are any other concerns or requirements.

**Comment by grrtrr** [comment]
Hi @waahm7,

 #587 only does truncated exponential backoff if the user explicitly opts into `AWS_EXPONENTIAL_BACKOFF_JITTER_DEFAULT`, all other variants still use unbounded exponential backoff
(the default is set to `s_compute_full_jitter`). 

This PR enabled unbounded back-off for all variants.

Is there an SDK that this is based upon? The `aws-sdk-cpp` for instance also does not truncate, its `DefaultRetryStrategy` just stops retrying after `maxRetries = 10`.

**Comment by waahm7** [comment]
Hi @grrtrr,

This is similar to [JAVA_SDK](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetrySetting.java#L66).
